1010: Upgrade react native
digitalfabrik/lunes-app pull request #1035
Opened 2024-10-31 13:09 UTC by steffenkleinle

### Short description

Upgrade react-native to v0.74.

### Proposed changes

- Upgrade react-native to v0.74
- Upgrade a few other libraries

### Side effects

- Hopefully none

### Testing

None. Please test TODO

### Resolved issues

Fixes: #1010 

---

2024-11-04 15:04 UTC, LeandraH reviewed
Amazing, thank you! Looks pretty good already, I could scan a QR code, I could use a picture from the gallery, and I could record a pronunciation when creating a new Vokabel, this all in real iOS 🥳 

I unfortunately also got two errors:

When trying to create a new Vokabel with a picture that I took with the camera within the app, I could take the picture but when hitting "Speichern", I got the following error:

```Sentry reported error:  [Error: “65893640-A69A-479F-B510-1BEF31C1F5CA.jpg” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.]```

After adding my own Vokabel with a picture from the gallery (which all worked), I could not open the card from the Vokabelliste, and got the following error message:

```The action 'NAVIGATE' with payload {"name":"UserVocabularyDetail","params":{"vocabularyItem":{"id":1,"word":"Test","article":{"id":1,"value":"der"},"images":[{"id":0,"image":"file:////var/mobile/Containers/Data/Application/0FF3AEA6-EB65-4D11-82C7-582C02D02B28/Documents/image-1-0.jpg"}],"audio":null,"alternatives":[],"type":"user-created"}}} was not handled by any navigator.

Do you have a screen named 'UserVocabularyDetail'?

If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.

This is a development-only warning and won't be shown in production.```

2024-11-06 10:50 UTC, steffenkleinle commented on ios/Lunes/Info.plist
> +	    <!-- Do not change NSAllowsArbitraryLoads to true, or you will risk app rejection! -->
Yes, it's a suggested change of the react-native upgrade helper. I'll check the formatting.

2024-11-06 10:53 UTC, steffenkleinle commented on android/app/src/debug/AndroidManifest.xml
> -    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
This is just the debug manifest, I am guessing this was due to flipper or some other dev thingy.
See https://react-native-community.github.io/upgrade-helper/?from=0.70.9&to=0.74.6#RnDiffApp-android-app-src-debug-AndroidManifest.xml

2024-11-19 13:01 UTC, steffenkleinle commented
> When trying to create a new Vokabel with a picture that I took with the camera within the app, I could take the picture but when hitting "Speichern", I got the following error:
> 
> `Sentry reported error: [Error: “65893640-A69A-479F-B510-1BEF31C1F5CA.jpg” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.]`

This happens on iOS only, correct? Did you test in both simulator/real device?

> After adding my own Vokabel with a picture from the gallery (which all worked), I could not open the card from the Vokabelliste, and got the following error message:
>
> Do you have a screen named 'UserVocabularyDetail'?
> If you're trying to navigate to a screen in a nested navigator, see https://reactnavigation.org/docs/nesting-navigators#navigating-to-a-screen-in-a-nested-navigator.`

I just checked and it seems like the problem already exists on main. I'll create an issue.

2024-11-19 15:19 UTC, LeandraH commented
> > When trying to create a new Vokabel with a picture that I took with the camera within the app, I could take the picture but when hitting "Speichern", I got the following error:
> > `Sentry reported error: [Error: “65893640-A69A-479F-B510-1BEF31C1F5CA.jpg” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.]`
> 
> This happens on iOS only, correct? Did you test in both simulator/real device? Also, does this always happen or just sometimes?

I just tested it again, I couldn't open the camera at all in emulated iOS. In real iOS, I got the error in three out of three attempts.

2024-12-04 10:45 UTC, steffenkleinle commented
> Oh, I also started getting a bunch of these warnings in my console:
> 
> `(ADVICE) View #1234 of type RCTView has a shadow set but cannot calculate shadow efficiently. Consider setting a solid background color to fix this, or apply the shadow to a more specific component`
> 
> It might be related to this: https://stackoverflow.com/questions/75355104/view-has-a-shadow-set-but-cannot-calculate-shadow-efficiently-in-react-native

@LeandraH I sadly can't reproduce this, can you tell where exactly you get those?

2024-12-04 11:12 UTC, steffenkleinle commented
> > > When trying to create a new Vokabel with a picture that I took with the camera within the app, I could take the picture but when hitting "Speichern", I got the following error:
> > > `Sentry reported error: [Error: “65893640-A69A-479F-B510-1BEF31C1F5CA.jpg” couldn’t be moved to “Documents” because either the former doesn’t exist, or the folder containing the latter doesn’t exist.]`
> > 
> > 
> > This happens on iOS only, correct? Did you test in both simulator/real device? Also, does this always happen or just sometimes?
> 
> I just tested it again, I couldn't open the camera at all in emulated iOS. In real iOS, I got the error in three out of three attempts.

I fixed the issue on the simulator (camera is not available but now the overlay is opened and an image can be selected). Selecting an image from the gallery and saving a new vocab works for me on simulated iOS.

Sadly, I have no way of investigating real iOS, could you perhaps take over @LeandraH? Thanks!

2024-12-04 16:28 UTC, LeandraH approved these changes
Woohoo! Tested on real iOS

2024-12-12 10:18 UTC, ztefanie requested changes
Thanks for taking care of this update :heart: 

Tested on Android real device and found a few errors:

adding a new word: Could not add a audio record for a new custom word. Error "startRecorder has already been called".
Steps to reproduce: "Meine Wörter" -> "Vokabel erstellen" -> "Audio aufnehmen" -> click on mircophone-icon -> See error

Adding a new word -> then go to the list of my words -> click on the item -> Error: "the action "navigate" with payload was not handled"

Menu is shown when navigating back on home screen after settings. Steps to reproduce: open home screen -> go to menu -> open "Lernbereiche verwalten" -> click "back". See menu is open on homescreen. Would expect it to be closed

2024-12-12 10:29 UTC, steffenkleinle commented
> adding a new word: Could not add a audio record for a new custom word. Error "startRecorder has already been called". Steps to reproduce: "Meine Wörter" -> "Vokabel erstellen" -> "Audio aufnehmen" -> click on mircophone-icon -> See error

Hmm, I guess I'll have another look. I really thought I tested this thoroughly and there were no more errors :/

> Adding a new word -> then go to the list of my words -> click on the item -> Error: "the action "navigate" with payload was not handled"

See https://github.com/digitalfabrik/lunes-app/issues/1037, already happens on main as well.

> Menu is shown when navigating back on home screen after settings. Steps to reproduce: open home screen -> go to menu -> open "Lernbereiche verwalten" -> click "back". See menu is open on homescreen. Would expect it to be closed

I'll check

2024-12-13 07:20 UTC, ztefanie commented
> 
> Menu is shown when navigating back on home screen after settings. Steps to reproduce: open home screen -> go to menu -> open "Lernbereiche verwalten" -> click "back". See menu is open on homescreen. Would expect it to be closed

https://github.com/digitalfabrik/lunes-app/issues/1046

2025-01-08 11:03 UTC, f1sh1918 requested changes
Unfortunately i found one issue
1. Create own vocabulary.
2. Go to detail view on the created vocabulary leads to

```js
 The action 'NAVIGATE' with payload {"name":"UserVocabularyDetail","params":{"vocabularyItem":{"id":1,"word":"Test","article":{"id":1,"value":"der"},"images":[{"id":0,"image":"file:////data/user/0/app.lunes/files/image-1-0-1736333899166.jpg"}],"audio":"file:////data/user/0/app.lunes/files/audio-1.mp4","alternatives":[],"type":"user-created"}}} was not handled by any navigator.

```

and nothing happens

2025-01-08 11:10 UTC, LeandraH commented
> Unfortunately i found one issue
> 
>     1. Create own vocabulary.
> 
>     2. Go to detail view on the created vocabulary leads to
> 
> 
> ```js
>  The action 'NAVIGATE' with payload {"name":"UserVocabularyDetail","params":{"vocabularyItem":{"id":1,"word":"Test","article":{"id":1,"value":"der"},"images":[{"id":0,"image":"file:////data/user/0/app.lunes/files/image-1-0-1736333899166.jpg"}],"audio":"file:////data/user/0/app.lunes/files/audio-1.mp4","alternatives":[],"type":"user-created"}}} was not handled by any navigator.
> ```
> 
> and nothing happens

That seems to be an issue on main, Steffen already opened #1037 for it

2025-01-08 11:13 UTC, f1sh1918 commented
> > Unfortunately i found one issue
> > ```
> > 1. Create own vocabulary.
> > 
> > 2. Go to detail view on the created vocabulary leads to
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> >  The action 'NAVIGATE' with payload {"name":"UserVocabularyDetail","params":{"vocabularyItem":{"id":1,"word":"Test","article":{"id":1,"value":"der"},"images":[{"id":0,"image":"file:////data/user/0/app.lunes/files/image-1-0-1736333899166.jpg"}],"audio":"file:////data/user/0/app.lunes/files/audio-1.mp4","alternatives":[],"type":"user-created"}}} was not handled by any navigator.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and nothing happens
> 
> That seems to be an issue on main, Steffen already opened #1037 for it

ok sorry i didn't get this. i pushed a commit to fix that @steffenkleinle 
So the mentioned issue should be fixed

2025-01-08 11:15 UTC, f1sh1918 approved these changes
Tested on android real device and ios simulator. works fine

2025-01-08 11:16 UTC, LeandraH commented
Amazing!

2025-01-08 11:32 UTC, steffenkleinle commented
@LeandraH @f1sh1918 you are not experiencing this issue? I could also reproduce this... have to have another look at some point...

> adding a new word: Could not add a audio record for a new custom word. Error "startRecorder has already been called".
Steps to reproduce: "Meine Wörter" -> "Vokabel erstellen" -> "Audio aufnehmen" -> click on mircophone-icon -> See error

2025-01-08 12:06 UTC, f1sh1918 commented
> @LeandraH @f1sh1918 you are not experiencing this issue? I could also reproduce this... have to have another look at some point...
> 
> > adding a new word: Could not add a audio record for a new custom word. Error "startRecorder has already been called".
> > Steps to reproduce: "Meine Wörter" -> "Vokabel erstellen" -> "Audio aufnehmen" -> click on mircophone-icon -> See error

i didn't test on ios real device but on android real device it worked for me (but android 11)

2025-01-08 14:31 UTC, LeandraH commented
> > @LeandraH @f1sh1918 you are not experiencing this issue? I could also reproduce this... have to have another look at some point...
> > > adding a new word: Could not add a audio record for a new custom word. Error "startRecorder has already been called".
> > > Steps to reproduce: "Meine Wörter" -> "Vokabel erstellen" -> "Audio aufnehmen" -> click on mircophone-icon -> See error
> 
> i didn't test on ios real device but on android real device it worked for me (but android 11) @steffenkleinle

Tested on a real iOS device and I could not reproduce the issue. When I only tapped on the microphone instead of holding it, I got the following warning, though: "Sending `rn-recordback` with no listeners registered." but that looks different (and like not a big issue) to me.

2025-01-09 19:38 UTC, lunars97 reviewed
I have been trying to solve this issue #1043 and upgrading the react-native seems to solve this issue :+1:

2025-01-09 19:52 UTC, lunars97 commented
I faced the error when I was viewing a vocabulary list words when I clicked on the button "Nächstes Wort" saying ` Warning: Error: Exception in HostFunction: Loss of precision during arithmetic conversion: (long long) 9.090909090909092` This error seems like because of the upgrade of the react-native-paper...

2025-01-10 10:26 UTC, LeandraH commented
> Hmm if none of you can reproduce this we might also just merge this? Could you all please test this on iOS simulator AND real device if possible please? This might only be a ios simulator problem?

I just tested it on an iOS simulator and couldn't reproduce the issue there either, neither yesterday on my iPhone. But Steffi said in her [comment](https://github.com/digitalfabrik/lunes-app/pull/1035#pullrequestreview-2498794907) that she had the issue on a real Android device.

2025-01-17 14:16 UTC, merged