LUN-12: Refactor css of component
digitalfabrik/lunes-app pull request #132
Opened 2021-08-26 15:17 UTC by ansamshtaiwi1

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-08-31 09:26 UTC, SteffiStuffel requested changes
Please rename PR so it starts with `LUN-12: Re....`

I made a lot of changeRequests here, feel free to contact me, why I suggested something if you don't see a benefit or suggest other solutions if you have something better in mind. We can also have a short call to discuss stuff or talk about this.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Loading.tsx
> +const Root = styled.View`
Something like LoadingContainer would be a better name.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    padding-top: 17;
Just merge paddings into one expression `padding: 17px 8px 17px 16px;`

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    align-self: center;
align-self can be removed i guess

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    width: 100%;
can be removed i guess

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    border-style: ${(prop: IMenuItemProps) => !prop.selected ? 'solid' : 'solid' };
ternery operator does not really make sense here.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    border-color: ${(prop: IMenuItemProps) => prop.selected? COLORS.white : COLORS.lunesBlackUltralight };
ternery does not really make sense here, as you put border-width to 0, so the color should not matter.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +const Wrapper = styled.View`
I think you can remove the Wrapper and put the margin into the ItemStyle.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +    margin-right: ${(prop: IMenuItemProps) => prop.selected ? wp('5%'): 0 };
I think you can just put `margin: 0px 16px 8px 16px;`and remove `margin-bottom: 8`

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +  onPress?: () => void
Please undo this. If changes are needed to the prop type see the solution i suggested above (in buttons.tsx). It does not make sense to make the e.g. onPress optional, as a MenuItem definatly should have a onPress-Prop

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +  children: ReactElement[] | string | undefined
also undo this please.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +const ItemTitleStyle = styled.Text`
itemTitle would be enough as a name

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/MenuItem.tsx
> +const ItemStyle = styled(Pressable)`
Just name it Item.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +const LightLabel = styled.Text`
here it ould make sense to have a generic class as Light and DarkLabel share all attributes but color. Or use props for setting the color.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +    justify-content: center;
justify-content does nothing

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +    margin-top: 0;
margin top does nothing

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +const ModalContainer = styled.Modal`
Does noting just remove ModalContainer completely

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +const Container = styled.View`
Rename to Overlay please.

2021-08-31 09:26 UTC, SteffiStuffel commented on src/components/Modal.tsx
> +const ModalStyle = styled.View`
Rename to ModalContainer please

2021-09-06 09:54 UTC, ansamshtaiwi1 commented on ios/Podfile.lock
>      - React-Core
I'll commit all similar tasks together

2021-09-06 10:01 UTC, ansamshtaiwi1 commented on ios/Podfile.lock
>      - React-Core
Should I change anything here?

2021-09-06 10:20 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  padding-top: 10;
done!

2021-09-06 11:32 UTC, klinzo commented on ios/Podfile.lock
>      - React-Core
The changes to `RNSoundPlayer` and `TextToSpeech` are definitely fine, we forgot them in #127 . Cocoa Pods version should only be upgraded together with the version resolution in `ios/Gemfile` I think, I don't see a reason why we shouldn't do that though.

2021-09-06 12:41 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  background-color: ${(prop: IButtonProps) => prop.disabled ? COLORS.lunesBlackUltralight :
is ### letter-spacing: 0.11 in em or px ?

2021-09-06 16:06 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  background-color: ${(prop: IButtonProps) => prop.disabled ? COLORS.lunesBlackUltralight :
px was added and ternery operator was replaced

2021-09-06 16:21 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  width: ${wp('70%')};
when I tried replace `wp('5%')`  to ` 5%` in` margin-left: ${(prop: IMenuItemProps) => prop.selected ? wp('5%'): 0 };` and similar, error appeared so I just left it as is.
do you have any suggestion?

2021-09-07 08:10 UTC, SteffiStuffel commented on src/components/Button.tsx
> +  width: ${wp('70%')};
you have to put it in single quotes `margin-right: ${(prop: IMenuItemProps) => prop.selected ? '5%': 0 };`

2021-09-14 11:11 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  width: ${wp('70%')};
@Taggotty 
when I tried to remove wp/hp, the size of elements changed, should I change the percentage or keep wp/hp as it?

2021-09-14 11:11 UTC, ansamshtaiwi1 commented on src/components/Button.tsx
> +  width: ${wp('70%')};
@Taggotty 
when I tried to remove wp/hp, the size of elements changed, should I change the percentage or keep wp/hp as it?

2021-09-15 11:02 UTC, Taggotty commented
Feel free to commit and push your changes, so I can check how you progress or need any help.

2021-09-29 07:07 UTC, SteffiStuffel approved these changes

2021-09-29 07:41 UTC, merged