Lun 13 refactor css for screens fixes
digitalfabrik/lunes-app pull request #143
Opened 2021-09-15 09:16 UTC by YasminNajar

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-09-20 10:06 UTC, Taggotty requested changes

2021-09-20 10:06 UTC, Taggotty commented on src/routes/ResultsOverviewScreen.tsx
> +  padding-left: 16px;
```suggestion
  padding: 17px 8px 17px 16px
```

2021-09-20 10:06 UTC, Taggotty commented on src/routes/write-exercise/components/AnswerSection.tsx
> +  border-color: ${(prop: StyledProps) => prop.StyledBorder};
```suggestion
const TextInputContainer = styled.View<{ styledBorderColor: string}>`
  width: 80%;
  height: 16%;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  border-width: 1px;
  border-radius: 2px;
  padding-right: 15px;
  padding-left: 15px;
  margin-top: 12%;
  margin-bottom: 12%;
  border-color: ${prop => prop.styledBorderColor};
```

2021-09-27 10:14 UTC, SteffiStuffel commented
Why are the fixes in separate PRs?

2021-09-27 10:38 UTC, Taggotty commented
> Why are the fixes in separate PRs?

@YasminNajar told me you told them to do them in a separate PR 😅

2021-09-27 10:41 UTC, Taggotty approved these changes

2021-09-27 10:45 UTC, YasminNajar commented
> 
> 
> Why are the fixes in separate PRs?

@SteffiStuffel We were informed by Aya that it's better to do a new branch for it, and Aya I think misunderstood something Steffi said, so I also thought that Steffi told Aya. It might have been a big misunderstanding

2021-09-27 10:47 UTC, merged