LUN 69: Play TTS for alternative solutions
digitalfabrik/lunes-app pull request #179
Opened 2021-11-02 16:15 UTC by klinzo

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-11-02 16:16 UTC, klinzo commented on src/routes/write-exercise/components/WriteExercise.tsx
> +      />
This is added, the rest stayed nearly the same.

2021-11-02 16:17 UTC, klinzo commented
Please test this. @SteffiStuffel where do we have alternatives?

2021-11-03 08:45 UTC, SteffiStuffel requested changes
Just tested this and get errors /unexpected behaviour:

When entering the correct (not alternative) solution, I get an no tts-engine-installed error, although it is installed, but also it is not needed.

When entering a correct alternative solution, the normal audio is played.

E.g. Zollstock has alternative solution Meterstab, it is in the Test-Module (Test -> Level2 -> Test)

2021-11-04 12:22 UTC, klinzo commented
> Just tested this and get errors /unexpected behaviour:
> 
> When entering the correct (not alternative) solution, I get an no tts-engine-installed error, although it is installed, but also it is not needed.
> 
> When entering a correct alternative solution, the normal audio is played.
> 
> E.g. Zollstock has alternative solution Meterstab, it is in the Test-Module (Test -> Level2 -> Test)

Should be fixed. Thanks!

2021-11-08 08:32 UTC, SteffiStuffel approved these changes
Tested again, works as expected

2021-11-08 08:33 UTC, SteffiStuffel commented
Can you add a release-note as well, please?

2021-11-08 14:43 UTC, f1sh1918 approved these changes
Tested on ios native, nice work :)

2021-11-08 14:53 UTC, merged