LUN-214: Missing-Connection-Adding-Discipline
digitalfabrik/lunes-app pull request #189
Opened 2021-11-23 13:32 UTC by f1sh1918

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

Please test this issue on IOS!

2021-11-23 14:00 UTC, klinzo requested changes
I think this should be fixed in the backend

2021-11-23 14:00 UTC, klinzo commented on src/services/helpers.ts
> +  return url.lastIndexOf('/') !== -1 ? url : `${url}/`
I don't think this works as expected. `'/asdf'.lastIndexOf('/')` also returns a value different to `-1` but has no trailing slash

2021-11-23 15:48 UTC, f1sh1918 commented on release-notes/unreleased/LUN-214-Missing-Connection-Adding-Discipline.yml
> +de: Fehler beim Hinzufügen individueller Bereiche behoben
removed

2021-11-23 17:02 UTC, f1sh1918 commented
> I think this should be fixed in the backend (at least permanently). As a short workaround this may be ok.

hm we can open a backend ticket, but as it looks its nothing to fix in a few minutes, so maybe we should maybe stick to this workaround and remove it lateron

2021-11-24 08:11 UTC, SteffiStuffel approved these changes
I cannot reproduce this when using Postman, both with and without slash works fine, not sure why this is. As this PR fixes a error we have, I would really appreciate if we can merge it soon.

2021-11-24 09:04 UTC, klinzo commented
When does this happen? Cannot reproduce this on iOS simulator

2021-11-24 11:02 UTC, merged