LUN-223: Add pre commit hook
digitalfabrik/lunes-app pull request #192
Opened 2021-11-29 13:08 UTC by klinzo

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-11-29 13:08 UTC, klinzo commented on .github/hooks/pre-commit
> +#!/bin/sh
Copied from https://github.com/Integreat/integreat-app/pull/521

2021-11-30 06:46 UTC, SteffiStuffel requested changes

2021-11-30 06:46 UTC, SteffiStuffel commented on .github/hooks/pre-commit
> +if [[ $(git status --short | grep .circleci) ]]; then
Think this does not really make sense. Remember the discussion we had on Integreat about this?
https://github.com/Integreat/integreat-app/pull/514/files

I would appreciate if, we copy this when the issue (IGAPP-855) is fixed or if you fix it now for lunes and integreat. We can also mark LUN-223-ticket as blocked by IGAPP-855.

2021-11-30 06:57 UTC, SteffiStuffel commented on .github/hooks/pre-commit
> +if [[ $(git status --short | grep .circleci) ]]; then
forget about this, too early in the morning. Everything fine.

2021-11-30 06:57 UTC, SteffiStuffel approved these changes

2021-11-30 14:54 UTC, Taggotty approved these changes

2021-11-30 17:01 UTC, merged