LUN-124 check modules enough words
digitalfabrik/lunes-app pull request #195
Opened 2021-12-01 11:01 UTC by Saraharar98

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-12-01 11:58 UTC, SteffiStuffel requested changes
Looks already good. :rocket: 
Just some small changes needed.

2021-12-01 11:58 UTC, SteffiStuffel commented on src/routes/ExercisesScreens.tsx
> +    if (item.title === 'Level 1' && numberOfChildren < 4) {
Please check if the `item.title` equals the constant from the labels.
(import labels-file and check for labels.exercises.wordChoice.title)

2021-12-01 11:58 UTC, SteffiStuffel commented on src/routes/ExercisesScreens.tsx
> +      Alert.alert('Not enough words')
Please also don't use this here as a string directly, but add a entry to the labels file, with a speaking name. German translation for the alert message should be: 'Die Übung ist für dieses Modul nicht möglich (zu wenig Wörter)'

2021-12-06 09:12 UTC, SteffiStuffel commented on src/constants/labels.json
> +      "speaking": "Die Übung ist für dieses Modul nicht möglich (zu wenig Wörter)"
oke sorry for the confusion, the name should not be `speaking`, i meant it should be a meaningful name. e.g. `errorWrongModuleSize`

2021-12-07 13:02 UTC, klinzo approved these changes
Good to merge your first PR :tada:

2021-12-10 18:07 UTC, Saraharar98 commented
RE-open PR

2021-12-14 13:55 UTC, Taggotty approved these changes
Tested on android emulator. Nice PR 🎉

2021-12-14 13:55 UTC, Taggotty commented on src/routes/ExercisesScreens.tsx
> +    if (item.title === labels.exercises.wordChoice.title && numberOfChildren < 4) {
labels isn't imported and it should be `discipline.numberOfChildren` I think.

2021-12-15 14:15 UTC, merged