Lun 203 rename menu item
digitalfabrik/lunes-app pull request #198
Opened 2021-12-07 19:53 UTC by Saraharar98

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2021-12-08 06:22 UTC, SteffiStuffel reviewed
Nice work, you just forget few occurrences. 

Please also rename the PR, it should start with `LUN-203: Ren....`

2021-12-08 06:22 UTC, SteffiStuffel commented on src/components/__tests__/CustomDisciplineMenuItem.spec.tsx
>    describe('CustomDisciplineMenuItem', () => {
Can you please rename here and also the adjust the filename?

2021-12-08 06:22 UTC, SteffiStuffel commented on src/components/__tests__/MenuItem.spec.tsx
> +    const renderMenuItem = (overrideProps: Partial<ComponentProps<typeof DisciplineItem>> = {}): RenderAPI => {
Please also rename this function

2021-12-08 06:22 UTC, SteffiStuffel commented on src/components/CustomDisciplineItem.tsx
>    refresh: () => void
This interface (line 41) should also be renamed.

2021-12-08 06:22 UTC, SteffiStuffel commented on src/components/DisciplineItem.tsx
>    onPress: () => void
Also this interface (line 39) should be renamed. Please name it `DisciplineItemProps`

2021-12-08 06:22 UTC, SteffiStuffel commented on src/components/__tests__/MenuItem.spec.tsx
>    describe('MenuItem', () => {
Please rename this, and also in line 11 the variable.

2021-12-10 12:49 UTC, klinzo approved these changes

2021-12-28 08:25 UTC, SteffiStuffel commented on src/components/__tests__/CustomDisciplineItem.spec.tsx
>    describe('CustomDisciplineMenuItem', () => {
please also rename the test here.

2021-12-28 08:25 UTC, SteffiStuffel commented on src/components/__tests__/DisciplineItem.spec.tsx
>    describe('MenuItem', () => {
Please rename the test here and also the title-constant in line 17.

2022-01-03 10:42 UTC, Taggotty approved these changes

2022-01-03 10:44 UTC, Taggotty requested changes

2022-01-03 10:44 UTC, Taggotty commented on src/components/__tests__/DisciplineItem.spec.tsx
>        const title = queryByText('Menu item title')
```suggestion
      const title = queryByText('Discipline Item title')
```

2022-01-03 10:44 UTC, Taggotty commented on src/components/__tests__/DisciplineItem.spec.tsx
>        const element = getByText('Menu item title')
```suggestion
      const element = getByText('Discipline Item title')
```

2022-01-04 10:19 UTC, SteffiStuffel approved these changes

2022-01-12 14:24 UTC, Taggotty approved these changes

2022-01-12 14:24 UTC, merged