LUN-242: Header text could use more space
digitalfabrik/lunes-app pull request #230
Opened 2022-02-02 13:47 UTC by klinzo

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2022-02-02 22:07 UTC, f1sh1918 commented on src/navigation/Navigator.tsx
> +    maxWidth: 60
setting a maxWidth will unfortunately not do the trick thats why spent so much time on it.
The right container has to stay also flexible. Thats why i worked with proportion or you use flex-basis

2022-02-02 22:07 UTC, f1sh1918 requested changes
Tested on android. Right header container is too small in some exercises
You could add in `ExerciseHeader.tsx` a separate style, so Navigation Header will not be affected only Exercise Header:
` headerRightContainerStyle: {maxWidth:100, paddingRight:15}`

![image](https://user-images.githubusercontent.com/37902063/152245480-5a423908-4e6e-44f6-a3ea-fd549af30de5.png)

2022-02-07 08:59 UTC, f1sh1918 commented on src/navigation/Navigator.tsx
> +    maxWidth: 60
yes because this container gonna be used in different cases

2022-02-07 14:15 UTC, klinzo commented on src/components/ExerciseHeader.tsx
> +  const progressText = numberOfWords !== 0 ? `${currentWord + 1} ${labels.general.header.of} ${numberOfWords}` : ''
Is this change fine @SteffiStuffel ?

2022-02-07 16:48 UTC, f1sh1918 approved these changes
Tested on android emulator and ios native. nice!

2022-02-08 08:01 UTC, SteffiStuffel approved these changes
Tested on browserstack android and ios.

2022-02-08 09:36 UTC, klinzo commented on src/components/ExerciseHeader.tsx
> +  const progressText = numberOfWords !== 0 ? `${currentWord + 1} ${labels.general.header.of} ${numberOfWords}` : ''
May have been wanted :)

2022-02-08 16:39 UTC, merged