LUN-264: Locking lane for exercises screen
digitalfabrik/lunes-app pull request #303
Opened 2022-05-25 08:10 UTC by SteffiStuffel

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2022-05-25 08:31 UTC, f1sh1918 requested changes
Tested on ios. For me every exercise page shoes the same progress, even i didn't start the exercise

<img src="https://user-images.githubusercontent.com/37902063/170217809-67adb92d-8da3-4af8-9837-76d558559c1a.png"  width="200" height="400" />

2022-05-25 08:31 UTC, f1sh1918 commented on src/routes/exercises/components/LockingLane.tsx
> +  margin: 10px;
pls use spacing from theme

2022-05-25 08:31 UTC, f1sh1918 commented on src/routes/exercises/components/LockingLane.tsx
> +  const colorPre = current.level < index ? 'black' : COLORS.lockingLane
i think all colors we use should be defined in `colors.ts`

2022-05-25 08:31 UTC, f1sh1918 commented on src/routes/exercises/ExercisesScreen.tsx
> +
rm empty line

2022-05-25 08:37 UTC, steffenkleinle reviewed
Is something else required for this to work? It shows the checkmark for all exercises except from an empty circle for the write exercise for me. When I complete the write exercise, it stays the same. This is the case for ALL disciplines. Looking good except from that though, I like the design.

2022-05-25 08:51 UTC, steffenkleinle approved these changes

2022-05-25 08:55 UTC, f1sh1918 approved these changes
sorry i didn't realize that the logic gonna be implemented in a separate issue. so everything is fine :) nice work!

2022-05-30 09:33 UTC, SteffiStuffel commented
> Is something else required for this to work? It shows the checkmark for all exercises except from an empty circle for the write exercise for me. When I complete the write exercise, it stays the same. This is the case for ALL disciplines. Looking good except from that though, I like the design.

This ticket is just for design. You can change hardCoded status in ExercisesScreen.tsx to see how it looks for no or one exercises finished. Logic will be done in next ticket.

2022-05-30 10:03 UTC, merged