LUN-269: Feedback for a word logic
digitalfabrik/lunes-app pull request #339
Opened 2022-08-03 12:38 UTC by SteffiStuffel

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2022-08-08 10:56 UTC, steffenkleinle reviewed
Tested on android :+1: When is it possible to give feedback for a discipline?
![image](https://user-images.githubusercontent.com/29095487/183402708-2a1633a1-5995-422e-97bc-7080065391fe.png)

2022-08-08 11:00 UTC, steffenkleinle requested changes
Suggest alternative word does not work

2022-08-11 07:53 UTC, SteffiStuffel commented
> Tested on android +1 When is it possible to give feedback for a discipline? ![image](https://user-images.githubusercontent.com/29095487/183402708-2a1633a1-5995-422e-97bc-7080065391fe.png)

Currently it is only possible via the api, but not in the app. No designs or feature request for this yet.

2022-08-11 08:10 UTC, SteffiStuffel commented on src/routes/vocabulary-detail/components/AlternativeWordsSection.tsx
> +      <SuggestionPressable>
Fixed, suggest alternative should work now.

2022-08-11 08:12 UTC, SteffiStuffel commented on src/components/ExerciseHeader.tsx
> +const MenuIconPrimary = styled(MenuIcon)`
Primary is our theme color, it is also named like this.

2022-08-11 08:12 UTC, SteffiStuffel commented on src/components/FeedbackModal.tsx
> +    sendFeedback(`${message} ${email}`, feedbackType, feedbackForId).catch(reportError).finally(onCloseFeedback)
no there isn't

2022-08-11 08:12 UTC, SteffiStuffel commented
> Suggest alternative word does not work

Fixed it.

2022-08-11 09:28 UTC, steffenkleinle approved these changes
Not tested again

2022-08-16 07:29 UTC, merged