LUN-415: Improve keyboard handling feedback modal
digitalfabrik/lunes-app pull request #364
Opened 2022-08-31 16:40 UTC by f1sh1918

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2022-09-03 13:02 UTC, steffenkleinle requested changes
Not working for me: 
<img src="https://user-images.githubusercontent.com/29095487/188271616-2233de98-f848-4086-ae9c-686a2fe8b054.png" height="400px" />

2022-09-13 06:58 UTC, f1sh1918 commented
> Not working for me: <img alt="" height="400px" src="https://user-images.githubusercontent.com/29095487/188271616-2233de98-f848-4086-ae9c-686a2fe8b054.png">

looks like behavior on android differs from ios :/ gonna check that

2022-09-13 14:20 UTC, f1sh1918 commented
Updated: Now i implemented a different handling for android and ios. please test on android again

2022-09-14 08:44 UTC, SteffiStuffel reviewed
On Android it is jumping twice, looking weird (see attached video). Also the "send" button disappears. I don't think it is intuitive, that you need to scroll.

https://user-images.githubusercontent.com/18463686/190106511-88b3bafb-8625-4044-8efb-84de00a53311.mp4

2022-09-14 08:47 UTC, steffenkleinle commented on src/hooks/useKeyboard.ts
> +// This hook listens to the keyboard and returns boolean whether keyboard is opened or closed & keyBoardHeight
Optional: I think it is pretty self explanatory so I'd remove the comment
```suggestion
```

2022-09-14 13:20 UTC, f1sh1918 commented
> On Android it is jumping twice, looking weird (see attached video). Also the "send" button disappears. I don't think it is intuitive, that you need to scroll.
> 
>  LUN-415.mp4

Well i dunno what to do against the jumping to be honest. Since this modal is very flexible you will reach the point where you have to scroll. We can not just resize it. So feel free for other suggestions than scrolling

2022-09-20 12:39 UTC, SteffiStuffel approved these changes
Not really happy with the current solution because of the jumping, but it is better than the status quo, so fine for me if it gets merged. Maybe you can open a ticket for fixing the jumping or we wait for UI/UX or testing to complain about ^^

2022-09-21 14:38 UTC, f1sh1918 commented
> Not really happy with the current solution because of the jumping, but it is better than the status quo, so fine for me if it gets merged. Maybe you can open a ticket for fixing the jumping or we wait for UI/UX or testing to complain about ^^

@SteffiStuffel 
Well the jumping issue is related to the resizing of the height that happens after the keyboard was opened. But we cannot resize the height before because we do not know the height of the keyboard before it did show.
We can only expect a particular keyboard height and calculate the Modal container height using it.
Then use this height even if keyboard is opened or closed

2022-09-22 06:21 UTC, SteffiStuffel commented
> 

I would appreciate most, if we just block rerendering until everything is calculated and then render it (maybe useLayoutEffect will help here), as the jumping is cause by first updating the padding and in a second step updating the height.

2022-09-26 11:03 UTC, f1sh1918 commented
> > 
> 
> I would appreciate most, if we just block rerendering until everything is calculated and then render it (maybe useLayoutEffect will help here), as the jumping is cause by first updating the padding and in a second step updating the height.

fixed the bottom positioning jumping but can not get the recalc height work before updating/rendering component. you can give it a try if you want. its not just by adding `useLayoutEffect`

2022-09-27 09:44 UTC, charludo approved these changes
(Tested on Android Emulator)
Very nice, works as intended. Never lost track of the cursor, and all fields + send button accessible without closing the keyboard.

Minor nitpick: at least on my rather low resolution emulator screen, the margins around the modal could be smaller to show a bit more of its content, which could be useful in some cases. For example, the bottom of the email field is just barely cut off after opening the keyboard

2022-09-27 10:33 UTC, merged