LUN-427: Optimize for tablet
digitalfabrik/lunes-app pull request #369
Opened 2022-09-20 17:21 UTC by f1sh1918

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

Please check all screen properly on android!! There is one small design difference for BottomTabs
Seems like the lib auto checks the space and put label and icons next to each other.
I think it looks fine for tablet? If not i can even change that

![image](https://user-images.githubusercontent.com/37902063/191323413-1e7ef38b-165f-43e9-815b-a018d83dcf4a.png)

2022-09-21 07:36 UTC, SteffiStuffel reviewed
Why is `hp` better than `wp`? A tablet is both heigher and wider.

Few small things i saw:
Padding of article hint is to big.
![LUN-427-articlehint](https://user-images.githubusercontent.com/18463686/191443261-8a2fb997-a4f2-4c2c-a6d5-34a5659abd8d.png)

Text-boxes border looks weird in feedback and search
![LUN-427-feedback](https://user-images.githubusercontent.com/18463686/191443269-298ae3dc-e2ed-44e0-a151-bac2de16ef29.png)
![LUN-427-leikon](https://user-images.githubusercontent.com/18463686/191443271-bf65756a-10cf-422e-a639-22053e611a16.png)

Menu is way to small
![LUN-427menu](https://user-images.githubusercontent.com/18463686/191443273-de322e80-175e-4823-9961-04a9b30ae1cf.png)

No results icon and text is too small
![LUN-427-no-results](https://user-images.githubusercontent.com/18463686/191443278-6b8d11d9-a083-466f-8b06-10515544d099.png)

2022-09-21 07:36 UTC, SteffiStuffel commented on release-notes/unreleased/LUN-427-optimize-for-tablet.yml
> +de: Lunes wurde für Tablets optimiert
Maybe `Optimierung für Tablets`. It's somehow seems strange to me to have the app name in a release note.

2022-09-21 10:19 UTC, f1sh1918 commented
> Why is `hp` better than `wp`? A tablet is both heigher and wider.
> 
> Few small things i saw: Padding of article hint is to big. ![LUN-427-articlehint](https://user-images.githubusercontent.com/18463686/191443261-8a2fb997-a4f2-4c2c-a6d5-34a5659abd8d.png)
> 
> Text-boxes border looks weird in feedback and search ![LUN-427-feedback](https://user-images.githubusercontent.com/18463686/191443269-298ae3dc-e2ed-44e0-a151-bac2de16ef29.png) ![LUN-427-leikon](https://user-images.githubusercontent.com/18463686/191443271-bf65756a-10cf-422e-a639-22053e611a16.png)
> 
> Menu is way to small ![LUN-427menu](https://user-images.githubusercontent.com/18463686/191443273-de322e80-175e-4823-9961-04a9b30ae1cf.png)
> 
> No results icon and text is too small ![LUN-427-no-results](https://user-images.githubusercontent.com/18463686/191443278-6b8d11d9-a083-466f-8b06-10515544d099.png)

Well thats what i explained in my presentation. If you use wp everything will scale 200%. Just put a mobile phone on a tablet (both portrait) and it will be self explaining.
Well strange border behavior on android...doesn't happen on ios :/ gonna check that

2022-09-21 11:09 UTC, SteffiStuffel commented
> 
> Well thats what i explained in my presentation. If you use wp everything will scale 200%. Just put a mobile phone on a tablet (both portrait) and it will be self explaining. Well strange border behavior on android...doesn't happen on ios :/ gonna check that

What do you men bei "put a mobile phone on a tablet"?

2022-09-21 11:14 UTC, f1sh1918 commented
> > Well thats what i explained in my presentation. If you use wp everything will scale 200%. Just put a mobile phone on a tablet (both portrait) and it will be self explaining. Well strange border behavior on android...doesn't happen on ios :/ gonna check that
> 
> What do you mean bei "put a mobile phone on a tablet"?

![image](https://user-images.githubusercontent.com/37902063/191489968-263559ef-c496-40d8-8791-fa14cab8f832.png)

Now you can image the scaling factor for width & height(i resized my tablet)

2022-09-21 11:31 UTC, SteffiStuffel commented
> > > Well thats what i explained in my presentation. If you use wp everything will scale 200%. Just put a mobile phone on a tablet (both portrait) and it will be self explaining. Well strange border behavior on android...doesn't happen on ios :/ gonna check that
> > 
> > 
> > What do you mean bei "put a mobile phone on a tablet"?
> 
> 
> Now you can image the scaling factor for width & height(i resized my tablet)

But as width differs more, woundn't width make more sense to use it for scaling or what am I missing?

2022-09-21 11:45 UTC, f1sh1918 commented
> > > > Well thats what i explained in my presentation. If you use wp everything will scale 200%. Just put a mobile phone on a tablet (both portrait) and it will be self explaining. Well strange border behavior on android...doesn't happen on ios :/ gonna check that
> > > 
> > > 
> > > What do you mean bei "put a mobile phone on a tablet"?
> > 
> > 
> > Now you can image the scaling factor for width & height(i resized my tablet)
> 
> But as width differs more, woundn't width make more sense to use it for scaling or what am I missing?

the point is you have to reflect the distance between the screen and you use a tablet in the same distance as a smart phone (not like laptop or monitor) if you increase everything 2x its way too big and looks ugly. You can try by yourself and change everything to wp and revert to the old percentage values...

2022-10-04 13:12 UTC, SteffiStuffel approved these changes
Looks good, have not tested again, as my emulator is not working.

2022-10-05 07:26 UTC, SteffiStuffel requested changes
I tested it on Pixel 4:

1) Images are no longer full width. left is the current main and right is LUN-427
![lun-427-image-width](https://user-images.githubusercontent.com/18463686/194003637-68860a80-07c6-4634-993d-5c2b7661537a.png)

2) Header has an margin, can also be seen in 1)
![lun-427-header height](https://user-images.githubusercontent.com/18463686/194003757-4c817165-06a8-4ff7-8bff-80c80d394f6f.png)

3) Icon of modal is too big (Happens in all modals e.g. cancel, feedback..)
![lun-427-modal](https://user-images.githubusercontent.com/18463686/194003897-f4fe5e44-5038-40a5-ae42-1e9af99d05a8.png)

4) When pressing on "cancel-exercise" icon in the header, it moved, while being pressed:
![lun-427-on-press](https://user-images.githubusercontent.com/18463686/194004074-208758a5-d4b1-4fbe-9fd3-f9ff6cc22cd3.png)

2022-10-06 11:16 UTC, f1sh1918 commented
> I tested it on Pixel 4:
> 
> 1. Images are no longer full width. left is the current main and right is LUN-427
>   
> 2. Header has an margin, can also be seen in 1)
>  
> 3. Icon of modal is too big (Happens in all modals e.g. cancel, feedback..)
>   
> 4. When pressing on "cancel-exercise" icon in the header, it moved, while being pressed:
>   
@SteffiStuffel 
1. this relies to this lib `react-native-image-zoom-viewer` and i have no clue how to fix for android (for ios everything is fine). Does not rely on my changes. Since there was no update since 2 years, we should think about moving to another lib tbh.
2. can not reproduce with my Pixel 4 Emulator nor real device
3.  fixed icon size
4. can not reproduce on emulator nor real device

![image](https://user-images.githubusercontent.com/37902063/194299148-4f1ee639-29df-417f-848f-232f005de3e5.png)

@steffenkleinle can you please test on emulator & real device, since steffi and me got different results on emulators which is very strange tbh

2022-10-06 13:01 UTC, sarahsporck reviewed
I think instead of taking half the wp value consider using about 0.6 of the wp. This seems to keep the proportions the same on at least my device. If it's a different factor for you we may have to re-discuss this. 

I'd also request that the images should use the full width available.

I think when adjusting to 0.6 of the wp value most issues will disappear from alone. 

I did not really look

2022-10-06 14:07 UTC, f1sh1918 commented on src/components/FavoriteButton.tsx
> +  min-height: ${hp('4%')}px;
well the correct factor is `0.56` if you compare width to height for iPhone5SE (320x560)
I don't think that this gonna fix the mentioned issues ;)

2022-10-06 14:08 UTC, f1sh1918 commented on src/components/FavoriteButton.tsx
> +  min-height: ${hp('4%')}px;
fixed this by using our spacings vars instead of hp `spacings.ts`

2022-10-06 21:01 UTC, f1sh1918 commented
> 4. When pressing on "cancel-exercise" icon in the header, it moved, while being pressed:
>  ok i found the issue tested on pixel 4, please recheck

2022-10-07 11:40 UTC, f1sh1918 commented
There is some weird behavior with the favorite button and the audio player. i have to check that maybe it relies on the svgs itself

2022-10-10 07:00 UTC, sarahsporck reviewed
I still feel as if the buttons are a little bit flat. However it is better now. What do you think @SteffiStuffel?

Further, is there a fixed process on how to calculate the hp values? E.g. if the design suggest a width of `100px` how would i calculate the corresponding hp value. Do we have this process documented somewhere?

2022-10-10 09:37 UTC, f1sh1918 commented
> I still feel as if the buttons are a little bit flat. However it is better now. What do you think @SteffiStuffel?
> 
> Further, is there a fixed process on how to calculate the hp values? E.g. if the design suggest a width of `100px` how would i calculate the corresponding hp value. Do we have this process documented somewhere?

We should define the percent of 1px i would add a comment to `spacings.ts`

2022-10-11 11:11 UTC, sarahsporck approved these changes
Tested on Android emulator. Really like the consistency in both tablet and mobile devices. Great Work!

2022-10-11 14:38 UTC, merged