LUN-440: Select image from gallery
digitalfabrik/lunes-app pull request #420
Opened 2023-02-14 17:17 UTC by LeandraH

This pull request belongs to the issue https://issues.tuerantuer.org/browse/LUN-440.

2023-02-14 20:37 UTC, f1sh1918 requested changes
Tested on android real device.
The permission request for for media is not showing up instead the `NoAuthView` shows up at instant

2023-02-14 20:37 UTC, f1sh1918 commented on src/routes/process-user-vocabulary/components/ImageSelectionOverlay.tsx
> +  margin: ${wp('0.6%')}px;
please use our spacing classes for margin

2023-02-14 21:00 UTC, f1sh1918 commented on src/routes/process-user-vocabulary/components/ImageSelectionOverlay.tsx
> +    Platform.OS === 'ios' ? PERMISSIONS.IOS.MEDIA_LIBRARY : PERMISSIONS.ANDROID.READ_MEDIA_IMAGES
requesting android permissions for media is quite more complicated depending on versions
```js
const androidMediaPermission = Platform.Version >= 33 ? PERMISSIONS.ANDROID.READ_MEDIA_IMAGES : PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE;
```
For Android13 you will also need another permission

On Android 13 the READ_EXTERNAL_STORAGE has been [replace](https://developer.android.com/about/versions/13/behavior-changes-13#granular-media-permissions) by READ_MEDIA_IMAGES and READ_MEDIA_VIDEO.
```js
<manifest>
...
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES"/>
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
...
<application>
```
Also check for
```js
<application
      android:requestLegacyExternalStorage="true"
      ```

2023-02-14 21:01 UTC, f1sh1918 commented on src/routes/process-user-vocabulary/components/ImageSelectionOverlay.tsx
> +    CameraRoll.getPhotos({ first: 30, assetType: 'Photos' })
I think the number should be increased

2023-02-14 21:13 UTC, f1sh1918 commented on src/routes/process-user-vocabulary/components/ImageSelectionOverlay.tsx
> +                <Pressable key={photo.node.timestamp} onPress={() => selectImage(photo.node.image.uri)}>
when i increased amount of images in the gallery, i got an duplicated key error. Not sure whats the reason for. Timestamps should be unique

2023-02-15 13:32 UTC, LeandraH commented
> Any reason why you didn't choose most popular library: https://www.npmjs.com/package/react-native-image-picker Just saw it could also take images. Not sure if it could maybe replace also the camera lib

Yes, I decided to go with the library that is recommended in the RN docs (https://reactnative.dev/docs/0.60/cameraroll). But I can switch it if you feel strongly about it. Or you can drop that into the ticket for replacing react-native-camera (https://issues.tuerantuer.org/browse/LUN-439).

2023-02-15 14:28 UTC, f1sh1918 commented
> > Any reason why you didn't choose most popular library: https://www.npmjs.com/package/react-native-image-picker Just saw it could also take images. Not sure if it could maybe replace also the camera lib
> 
> Yes, I decided to go with the library that is recommended in the RN docs (https://reactnative.dev/docs/0.60/cameraroll). But I can switch it if you feel strongly about it. Or you can drop that into the ticket for replacing react-native-camera (https://issues.tuerantuer.org/browse/LUN-439).

Well actually it's your ticket. So it was just a recomendación. I just think if we use one highly supported lib for two features it's better to maintain than two different libs. We could discuss this at the conference

2023-02-16 08:11 UTC, SteffiStuffel commented
> 
> I just think if we use one highly supported lib for two features it's better to maintain than two different libs. We could discuss this at the conference

I think about this like Andy, but i am also fine with merging this now, change it later in the other ticket, although I think it would make sense to change it now, as then we/martin only need to test this one time and so on. Let me know how you decided and if i should review this.

2023-02-16 11:30 UTC, LeandraH commented
Okay, I'll switch to the image-picker then, thanks for your input :)

2023-03-03 10:07 UTC, LeandraH commented
I changed the package to react-native-image-crop-picker now. react-native-image-picker unfortunately can't handle the iOS' limited permission (https://github.com/react-native-image-picker/react-native-image-picker/issues/1749) but the crop-picker also has a camera function, so we can probably replace react-native-camera with it as well.

2023-03-06 12:50 UTC, SteffiStuffel reviewed
Tested on Android emulator. Please squash the commits.

2023-03-06 12:50 UTC, SteffiStuffel commented on release-notes/unreleased/LUN-440-select-image-from-gallery.yml
> +de: Nutzer:innen können nun Bilder für eigene Vokablen aus der Fotomediathek benutzen.
Please delete these release notes, there will be one release note for the whole own vocabulary feature.

2023-03-07 06:51 UTC, SteffiStuffel approved these changes
Nice work. Please squash the commits.

2023-03-13 10:46 UTC, f1sh1918 approved these changes
Tested on android and ios!
Nicely done :)

2023-03-13 10:46 UTC, f1sh1918 commented on src/routes/process-user-vocabulary/components/ImageSelectionOverlay.tsx
> +    // eslint-disable-next-line no-magic-numbers
please set a constant for the platform version and remove this :)

2023-03-13 15:35 UTC, merged