LUN-520: Fix editing bug
digitalfabrik/lunes-app pull request #454
Opened 2023-06-29 14:20 UTC by LeandraH

This pull request belongs to the issue https://issues.tuerantuer.org/browse/LUN-520.
The phone automatically saves the photo to its library already, we don't need to do that a second time with a new name. When editing, we were trying to save the picture a third time, with the same new name, which Android seems to ignore and iOS seems to not.

To test: I managed to reproduce this on my real iPhone, not on an emulated one.

2023-07-03 11:53 UTC, steffenkleinle approved these changes
Works as expected, tested on android. Could you please check the linked issue in jira and reject if it is referring to the same issue?

2023-07-03 11:53 UTC, steffenkleinle commented on src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
> +      const imagePaths = await Promise.all(images.map(async (image, index) => ({ id: index, image })))
I think there is no need for a promise/async anymore

2023-07-10 07:37 UTC, SteffiStuffel requested changes

2023-07-10 07:37 UTC, SteffiStuffel commented on src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
> +      const imagePaths = images.map((image, index) => ({ id: index, image }))
You cannot remove this part, as it is really important.
We move these images as when they are taken in the app, they are only saved to a cache, to persist them and see them later, we need to save them to a permanent path. You can see this error, when you create an own vocabulary, then close the app, clear the app cache and reopen the app, then the image of this word is not available. 
As this seems to be related to the sentry bug, you should investigate, why the id counter does not work properly and this bug occurs.

2023-07-10 12:47 UTC, SteffiStuffel requested changes
Now it is not possible to change the image of a word. Steps to reproduce:
create a word with an image
save
edit the image by removing the existing image and then adding a new one.
Result: Still the old image is displayed.

So we need to delete old images if they are removed.

2023-07-11 07:06 UTC, SteffiStuffel approved these changes
Almost there, we now need to delete images from file storage, if they are deleted by the app. Feel free to create a own ticket for this, if you do not want to do it in this PR.

2023-07-11 12:55 UTC, LeandraH commented
Sounds good, I'll do that separately since we aren't doing it so far.

2023-07-11 12:59 UTC, merged