LUN-524: Close dropdown when clicking outside
digitalfabrik/lunes-app pull request #456
Opened 2023-07-10 08:40 UTC by SteffiStuffel

This pull request belongs to an issue on our [bugtracker](https://issues.tuerantuer.org/secure/RapidBoard.jspa?rapidView=27&view=detail).
You can find it there by looking for an issue with the key which is mentioned in the title of this pull request.
It starts with the keyword _LUN_.

2023-07-10 11:50 UTC, LeandraH reviewed
Works nicely except when I tap on any other interactive element (the field to edit the word, the button to record an audio, the button to save), then the dropdown stays open.

2023-07-11 09:24 UTC, SteffiStuffel commented
> Works nicely except when I tap on any other interactive element (the field to edit the word, the button to record an audio, the button to save), then the dropdown stays open.

You are right, thank you. Fixed it.

2023-07-12 08:45 UTC, sarahsporck requested changes
Tested in emulated Android and simulated ios. When now trying to select an article nothing is selected.

2023-07-17 12:08 UTC, SteffiStuffel commented
I had a closer look at this, and think the best is to replace the Dropdown library with an other dropdown library. Unfortunately styling needs to be done with StyleSheets. Feel free to suggest better options, as I am aware this is not perfect, buy I couldn't find any better solution.

2023-07-17 14:28 UTC, LeandraH approved these changes
Looks good, tested in emulated iOS. I don't have a better idea for the StyleSheets either :(

2023-07-18 05:56 UTC, SteffiStuffel commented on src/components/Dropdown.tsx
> +  value: string | null
Yes, I need to fix this

2023-07-20 14:05 UTC, sarahsporck approved these changes
I installed pods for you. Android works fine :)

2023-07-20 14:05 UTC, sarahsporck commented on src/components/Dropdown.tsx
> +  iconStyle: {
This is required so that the icon is rendered on ios

2023-07-24 06:58 UTC, merged