LUN-528: Delete deleted photos on saving
digitalfabrik/lunes-app pull request #460
Opened 2023-07-19 15:39 UTC by LeandraH

This pull request belongs to the issue https://issues.tuerantuer.org/browse/LUN-528 on our bug tracker.

2023-07-24 07:19 UTC, SteffiStuffel requested changes
If a word is deleted the images should also be deleted.
Also if changing the article of a word, all existing and unmodified images are renamed. I think this does not really make sense.
Deleted images are correctly deleted :+1:

2023-07-28 07:08 UTC, sarahsporck commented
@LeandraH somehow you have all the picker changes on this pr. Would you mind rebasing :)

2023-08-07 07:32 UTC, SteffiStuffel requested changes
Unfortunately this is not working, steps to reproduce:
1) Create a word with one image and save it
2) Create a word with three images and save it
3) Delete the first word (with one image)

Results:
Three images are deleted

Expected result:
Only the one image of the first word should be deleted

2023-08-16 14:33 UTC, LeandraH commented
Ouch, good catch, thanks!

2023-08-17 07:27 UTC, SteffiStuffel commented
> Ouch, good catch, thanks!

Thanks for fixing. Unfortunately this is still not working properly. Steps to reproduce:
1. Create a word with two images.
2. Save the word
3. Edit the word
4. delete one image
5. create a new image
6. save it

Expected results: One "old" image is there and one "new" image.

Actual results: Both old images are there the new images is not saved

2023-08-21 12:40 UTC, LeandraH commented
Ooof, sorry, it should work now? I tested it quite a bit and couldn't find more problems 🤞

2023-08-23 06:00 UTC, sarahsporck approved these changes
Tested on Android emulator. Seems to be working fine. 👍🏼

2023-08-23 08:57 UTC, LeandraH commented on src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
> +  // TODO: find the new number
Sorry, WIP comment 🤦

2023-08-28 05:51 UTC, SteffiStuffel approved these changes
Looks good, tested on Android :tada:

2023-08-28 05:51 UTC, SteffiStuffel commented on src/routes/process-user-vocabulary/UserVocabularyProcessScreen.tsx
> +          const imageHasBeenSavedPreviously = itemToEdit?.images.map(image => image.image).includes(image)
naming this condition makes code much more readable :+1:

2023-08-28 05:56 UTC, SteffiStuffel commented
Squashing commits would be nice

2023-08-28 07:55 UTC, merged